name: 'Netlify Deploy'

on:
  push:
    branches: 
     - staging

jobs:
  deploy:
    name: 'Build and Deploy to Netlify'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      
      - name: 'Setup NodeJS'
        uses: actions/setup-node@v1
        with:
          node-version: '16.19.1'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Add .env file'
        run: |
          touch .env
          echo "${{ env.ENV_FILE }}" >> .env

      - name: 'Build'
        run: npm run build

      - uses: jsmrcaga/action-netlify-deploy@master
        # run: curl -X POST -d {} ${{ secrets.NETLIFY_AUTO_DEPLOY }}
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_AUTO_DEPLOY }}
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: .output/public
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
